In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("/content/Day_6 Sample_dataSet.xlsx")

In [3]:
df

,Id,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
0,1,Abi,abi1@gmail.com,Female,10,100,98,97,99,100,100,98,A+
1,2,Ram,ram2@gmail.com,Male,4,78,80,82,79,85,81,77,A
2,3,Priya,priya3@gmail.com,Female,1,50,55,58,52,60,57,54,C
3,4,Divya,divya4@gmail.com,Female,5,90,92,88,91,94,89,93,A+
4,5,Kavin,kavin5@gmail.com,Male,3,72,74,70,73,76,71,75,B+
5,6,Meena,meena6@gmail.com,Female,6,88,84,86,90,89,85,87,A
6,7,Arjun,arjun7@gmail.com,Male,2,61,63,67,65,68,70,66,B
7,8,Sneha,sneha8@gmail.com,Female,4,79,82,80,78,84,83,81,A
8,9,Rahul,rahul9@gmail.com,Male,1,45,50,48,46,52,49,47,C
9,10,Anu,anu10@gmail.com,Female,5,91,89,92,90,95,93,94,A+
10,11,Seeman,seeman11@gmail.com,Male,3,74,71,73,76,72,75,70,B+
11,12,Keerthi,keerthi12@gmail.com,Female,2,67,69,71,68,73,74,72,B
12,13,Vicky,vicky13@gmail.com,Male,6,85,87,84,88,90,86,89,A
13,14,Nisha,nisha14@gmail.com,Female,4,80,83,81,79,82,84,80,A
14,15,Hari,hari15@gmail.com,Male,1,55,58,56,54,60,57,59,C+
15,16,Lavanya,lavanya16@gmail.com,Female,5,93,91,94,92,96,95,97,A+
16,17,Ajay,ajay17@gmail.com,Male,2,62,64,66,63,67,68,65,B
17,18,Pooja,pooja18@gmail.com,Female,3,76,78,74,77,79,80,75,B+
18,19,Sanjay,sanjay19@gmail.com,Male,4,82,85,83,81,86,84,82,A
19,20,Rekha,rekha20@gmail.com,Female,6,89,90,91,88,92,93,90,A+

In [4]:
df.head()

,Id,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
0,1,Abi,abi1@gmail.com,Female,10,100,98,97,99,100,100,98,A+
1,2,Ram,ram2@gmail.com,Male,4,78,80,82,79,85,81,77,A
2,3,Priya,priya3@gmail.com,Female,1,50,55,58,52,60,57,54,C
3,4,Divya,divya4@gmail.com,Female,5,90,92,88,91,94,89,93,A+
4,5,Kavin,kavin5@gmail.com,Male,3,72,74,70,73,76,71,75,B+

In [5]:
df.tail()

,Id,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
15,16,Lavanya,lavanya16@gmail.com,Female,5,93,91,94,92,96,95,97,A+
16,17,Ajay,ajay17@gmail.com,Male,2,62,64,66,63,67,68,65,B
17,18,Pooja,pooja18@gmail.com,Female,3,76,78,74,77,79,80,75,B+
18,19,Sanjay,sanjay19@gmail.com,Male,4,82,85,83,81,86,84,82,A
19,20,Rekha,rekha20@gmail.com,Female,6,89,90,91,88,92,93,90,A+

In [7]:
df.shape

(20, 13)

In [8]:
df.columns

Index(['Id', 'Student_Name', 'Email', 'Gender', 'weekly_self_study_hours',
       'math_score', 'history_score', 'physics_score', 'chemistry_score',
       'biology_score', 'english_score', 'geography_score', 'Grade'],
      dtype='object')

In [9]:
df.dtypes

Id                          int64
Student_Name               object
Email                      object
Gender                     object
weekly_self_study_hours     int64
math_score                  int64
history_score               int64
physics_score               int64
chemistry_score             int64
biology_score               int64
english_score               int64
geography_score             int64
Grade                      object
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Id                       20 non-null     int64
 1   Student_Name             20 non-null     object
 2   Email                    20 non-null     object
 3   Gender                   20 non-null     object
 4   weekly_self_study_hours  20 non-null     int64
 5   math_score               20 non-null     int64
 6   history_score            20 non-null     int64
 7   physics_score            20 non-null     int64
 8   chemistry_score          20 non-null     int64
 9   biology_score            20 non-null     int64
 10  english_score            20 non-null     int64
 11  geography_score          20 non-null     int64
 12  Grade                    20 non-null     object
dtypes: int64(9), object(4)
memory usage: 2.2+ KB

In [13]:
df["math_score"].sum()

np.int64(1517)

In [14]:
df["physics_score"].mean()

np.float64(77.05)

In [16]:
df["chemistry_score"].min()

46

In [18]:
df["biology_score"].max()

100

In [19]:
df["Student_Name"].unique()

array(['Abi', 'Ram', 'Priya', 'Divya', 'Kavin', 'Meena', 'Arjun', 'Sneha',
       'Rahul', 'Anu', 'Seeman', 'Keerthi', 'Vicky', 'Nisha', 'Hari',
       'Lavanya', 'Ajay', 'Pooja', 'Sanjay', 'Rekha'], dtype=object)

In [22]:
df.drop("Student_Name",axis=1)

,Id,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
0,1,abi1@gmail.com,Female,10,100,98,97,99,100,100,98,A+
1,2,ram2@gmail.com,Male,4,78,80,82,79,85,81,77,A
2,3,priya3@gmail.com,Female,1,50,55,58,52,60,57,54,C
3,4,divya4@gmail.com,Female,5,90,92,88,91,94,89,93,A+
4,5,kavin5@gmail.com,Male,3,72,74,70,73,76,71,75,B+
5,6,meena6@gmail.com,Female,6,88,84,86,90,89,85,87,A
6,7,arjun7@gmail.com,Male,2,61,63,67,65,68,70,66,B
7,8,sneha8@gmail.com,Female,4,79,82,80,78,84,83,81,A
8,9,rahul9@gmail.com,Male,1,45,50,48,46,52,49,47,C
9,10,anu10@gmail.com,Female,5,91,89,92,90,95,93,94,A+
10,11,seeman11@gmail.com,Male,3,74,71,73,76,72,75,70,B+
11,12,keerthi12@gmail.com,Female,2,67,69,71,68,73,74,72,B
12,13,vicky13@gmail.com,Male,6,85,87,84,88,90,86,89,A
13,14,nisha14@gmail.com,Female,4,80,83,81,79,82,84,80,A
14,15,hari15@gmail.com,Male,1,55,58,56,54,60,57,59,C+
15,16,lavanya16@gmail.com,Female,5,93,91,94,92,96,95,97,A+
16,17,ajay17@gmail.com,Male,2,62,64,66,63,67,68,65,B
17,18,pooja18@gmail.com,Female,3,76,78,74,77,79,80,75,B+
18,19,sanjay19@gmail.com,Male,4,82,85,83,81,86,84,82,A
19,20,rekha20@gmail.com,Female,6,89,90,91,88,92,93,90,A+

In [23]:
df.rename(columns={"Student_Name":"Name"})

,Id,Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
0,1,Abi,abi1@gmail.com,Female,10,100,98,97,99,100,100,98,A+
1,2,Ram,ram2@gmail.com,Male,4,78,80,82,79,85,81,77,A
2,3,Priya,priya3@gmail.com,Female,1,50,55,58,52,60,57,54,C
3,4,Divya,divya4@gmail.com,Female,5,90,92,88,91,94,89,93,A+
4,5,Kavin,kavin5@gmail.com,Male,3,72,74,70,73,76,71,75,B+
5,6,Meena,meena6@gmail.com,Female,6,88,84,86,90,89,85,87,A
6,7,Arjun,arjun7@gmail.com,Male,2,61,63,67,65,68,70,66,B
7,8,Sneha,sneha8@gmail.com,Female,4,79,82,80,78,84,83,81,A
8,9,Rahul,rahul9@gmail.com,Male,1,45,50,48,46,52,49,47,C
9,10,Anu,anu10@gmail.com,Female,5,91,89,92,90,95,93,94,A+
10,11,Seeman,seeman11@gmail.com,Male,3,74,71,73,76,72,75,70,B+
11,12,Keerthi,keerthi12@gmail.com,Female,2,67,69,71,68,73,74,72,B
12,13,Vicky,vicky13@gmail.com,Male,6,85,87,84,88,90,86,89,A
13,14,Nisha,nisha14@gmail.com,Female,4,80,83,81,79,82,84,80,A
14,15,Hari,hari15@gmail.com,Male,1,55,58,56,54,60,57,59,C+
15,16,Lavanya,lavanya16@gmail.com,Female,5,93,91,94,92,96,95,97,A+
16,17,Ajay,ajay17@gmail.com,Male,2,62,64,66,63,67,68,65,B
17,18,Pooja,pooja18@gmail.com,Female,3,76,78,74,77,79,80,75,B+
18,19,Sanjay,sanjay19@gmail.com,Male,4,82,85,83,81,86,84,82,A
19,20,Rekha,rekha20@gmail.com,Female,6,89,90,91,88,92,93,90,A+

In [24]:
df.query("math_score>90")

,Id,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
0,1,Abi,abi1@gmail.com,Female,10,100,98,97,99,100,100,98,A+
9,10,Anu,anu10@gmail.com,Female,5,91,89,92,90,95,93,94,A+
15,16,Lavanya,lavanya16@gmail.com,Female,5,93,91,94,92,96,95,97,A+

In [27]:
df[df["geography_score"]==90]

,Id,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
19,20,Rekha,rekha20@gmail.com,Female,6,89,90,91,88,92,93,90,A+

In [28]:
df["Student_Name"]

0         Abi
1         Ram
2       Priya
3       Divya
4       Kavin
5       Meena
6       Arjun
7       Sneha
8       Rahul
9         Anu
10     Seeman
11    Keerthi
12      Vicky
13      Nisha
14       Hari
15    Lavanya
16       Ajay
17      Pooja
18     Sanjay
19      Rekha
Name: Student_Name, dtype: object

In [31]:
df[["Student_Name","Id"]]

   Student_Name  Id
0           Abi   1
1           Ram   2
2         Priya   3
3         Divya   4
4         Kavin   5
5         Meena   6
6         Arjun   7
7         Sneha   8
8         Rahul   9
9           Anu  10
10       Seeman  11
11      Keerthi  12
12        Vicky  13
13        Nisha  14
14         Hari  15
15      Lavanya  16
16         Ajay  17
17        Pooja  18
18       Sanjay  19
19        Rekha  20

In [32]:
df["Student_Name"].str.upper()

0         ABI
1         RAM
2       PRIYA
3       DIVYA
4       KAVIN
5       MEENA
6       ARJUN
7       SNEHA
8       RAHUL
9         ANU
10     SEEMAN
11    KEERTHI
12      VICKY
13      NISHA
14       HARI
15    LAVANYA
16       AJAY
17      POOJA
18     SANJAY
19      REKHA
Name: Student_Name, dtype: object

In [33]:
df["Student_Name"].str.swapcase()

0         aBI
1         rAM
2       pRIYA
3       dIVYA
4       kAVIN
5       mEENA
6       aRJUN
7       sNEHA
8       rAHUL
9         aNU
10     sEEMAN
11    kEERTHI
12      vICKY
13      nISHA
14       hARI
15    lAVANYA
16       aJAY
17      pOOJA
18     sANJAY
19      rEKHA
Name: Student_Name, dtype: object

In [34]:
df[df["history_score"].between(80,90)]

,Id,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
1,2,Ram,ram2@gmail.com,Male,4,78,80,82,79,85,81,77,A
5,6,Meena,meena6@gmail.com,Female,6,88,84,86,90,89,85,87,A
7,8,Sneha,sneha8@gmail.com,Female,4,79,82,80,78,84,83,81,A
9,10,Anu,anu10@gmail.com,Female,5,91,89,92,90,95,93,94,A+
12,13,Vicky,vicky13@gmail.com,Male,6,85,87,84,88,90,86,89,A
13,14,Nisha,nisha14@gmail.com,Female,4,80,83,81,79,82,84,80,A
18,19,Sanjay,sanjay19@gmail.com,Male,4,82,85,83,81,86,84,82,A
19,20,Rekha,rekha20@gmail.com,Female,6,89,90,91,88,92,93,90,A+

In [36]:
df["Student_Name"].str.len()

0     3
1     3
2     5
3     5
4     5
5     5
6     5
7     5
8     5
9     3
10    6
11    7
12    5
13    5
14    4
15    7
16    4
17    5
18    6
19    5
Name: Student_Name, dtype: int64

In [37]:
df["Student_Name"].str.contains("A")

0      True
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17    False
18    False
19    False
Name: Student_Name, dtype: bool

In [38]:
df["Student_Name"].str.startswith("A")

0      True
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17    False
18    False
19    False
Name: Student_Name, dtype: bool

In [40]:
df["Student_Name"].str.endswith("a")

0     False
1     False
2      True
3      True
4     False
5      True
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15     True
16    False
17     True
18    False
19     True
Name: Student_Name, dtype: bool

In [42]:
df1=pd.read_csv("/content/student-scores_DATASET(cleaned).csv")

In [43]:
df1

,Id,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [45]:
pd.merge(df,df1,on="Id")

,Id,Student_Name,Email_x,Gender_x,weekly_self_study_hours_x,math_score_x,history_score_x,physics_score_x,chemistry_score_x,biology_score_x,...,math_score_y,history_score_y,physics_score_y,chemistry_score_y,biology_score_y,english_score_y,geography_score_y,Grade_y,Gender_y,Email_y
0,1,Abi,abi1@gmail.com,Female,10,100,98,97,99,100,...,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,Ram,ram2@gmail.com,Male,4,78,80,82,79,85,...,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,Priya,priya3@gmail.com,Female,1,50,55,58,52,60,...,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,Divya,divya4@gmail.com,Female,5,90,92,88,91,94,...,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,Kavin,kavin5@gmail.com,Male,3,72,74,70,73,76,...,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
5,6,Meena,meena6@gmail.com,Female,6,88,84,86,90,89,...,93,100,67,78,72,80,84,Good,Male,student6@gmail.com
6,7,Arjun,arjun7@gmail.com,Male,2,61,63,67,65,68,...,99,96,97,73,88,76,64,Good,Female,student7@gmail.com
7,8,Sneha,sneha8@gmail.com,Female,4,79,82,80,78,84,...,95,95,82,63,84,70,85,Good,Female,student8@gmail.com
8,9,Rahul,rahul9@gmail.com,Male,1,45,50,48,46,52,...,94,68,94,85,81,74,72,Good,Female,student9@gmail.com
9,10,Anu,anu10@gmail.com,Female,5,91,89,92,90,95,...,98,69,88,71,67,71,73,Good,Female,student10@gmail.com
10,11,Seeman,seeman11@gmail.com,Male,3,74,71,73,76,72,...,65,60,97,94,71,81,66,Good,Female,student11@gmail.com
11,12,Keerthi,keerthi12@gmail.com,Female,2,67,69,71,68,73,...,80,61,100,65,87,64,61,Good,Female,student12@gmail.com
12,13,Vicky,vicky13@gmail.com,Male,6,85,87,84,88,90,...,94,59,69,67,89,65,73,Good,Female,student13@gmail.com
13,14,Nisha,nisha14@gmail.com,Female,4,80,83,81,79,82,...,66,94,86,100,57,90,63,Good,Female,student14@gmail.com
14,15,Hari,hari15@gmail.com,Male,1,55,58,56,54,60,...,96,90,86,92,92,95,87,Excellent,Male,student15@gmail.com
15,16,Lavanya,lavanya16@gmail.com,Female,5,93,91,94,92,96,...,94,50,78,64,79,74,84,Good,Male,student16@gmail.com
16,17,Ajay,ajay17@gmail.com,Male,2,62,64,66,63,67,...,92,64,93,91,80,89,72,Good,Male,student17@gmail.com
17,18,Pooja,pooja18@gmail.com,Female,3,76,78,74,77,79,...,86,83,85,79,93,76,77,Good,Female,student18@gmail.com
18,19,Sanjay,sanjay19@gmail.com,Male,4,82,85,83,81,86,...,92,87,92,99,97,87,86,Excellent,Male,student19@gmail.com
19,20,Rekha,rekha20@gmail.com,Female,6,89,90,91,88,92,...,99,65,98,75,66,72,100,Good,Male,student20@gmail.com

In [46]:
df["math_score"].astype(float)

0     100.0
1      78.0
2      50.0
3      90.0
4      72.0
5      88.0
6      61.0
7      79.0
8      45.0
9      91.0
10     74.0
11     67.0
12     85.0
13     80.0
14     55.0
15     93.0
16     62.0
17     76.0
18     82.0
19     89.0
Name: math_score, dtype: float64

In [67]:
print(df.join(df1,lsuffix="_left",rsuffix="_right"))

    Id_left  Age Student_Name           Email_left Gender_left  \
0         1   20          Abi       abi1@gmail.com      Female
1         2   20          Ram       ram2@gmail.com        Male
2         3   20        Priya     priya3@gmail.com      Female
3         4   20        Divya     divya4@gmail.com      Female
4         5   20        Kavin     kavin5@gmail.com        Male
5         6   20        Meena     meena6@gmail.com      Female
6         7   20        Arjun     arjun7@gmail.com        Male
7         8   20        Sneha     sneha8@gmail.com      Female
8         9   20        Rahul     rahul9@gmail.com        Male
9        10   20          Anu      anu10@gmail.com      Female
10       11   20       Seeman   seeman11@gmail.com        Male
11       12   20      Keerthi  keerthi12@gmail.com      Female
12       13   20        Vicky    vicky13@gmail.com        Male
13       14   20        Nisha    nisha14@gmail.com      Female
14       15   20         Hari     hari15@gmail.com        Male
15       16   20      Lavanya  lavanya16@gmail.com      Female
16       17   20         Ajay     ajay17@gmail.com        Male
17       18   20        Pooja    pooja18@gmail.com      Female
18       19   20       Sanjay   sanjay19@gmail.com        Male
19       20   20        Rekha    rekha20@gmail.com      Female

    weekly_self_study_hours_left  math_score_left  history_score_left  \
0                             10              100                  98
1                              4               78                  80
2                              1               50                  55
3                              5               90                  92
4                              3               72                  74
5                              6               88                  84
6                              2               61                  63
7                              4               79                  82
8                              1               45                  50
9                              5               91                  89
10                             3               74                  71
11                             2               67                  69
12                             6               85                  87
13                             4               80                  83
14                             1               55                  58
15                             5               93                  91
16                             2               62                  64
17                             3               76                  78
18                             4               82                  85
19                             6               89                  90

    physics_score_left  chemistry_score_left  ...  math_score_right  \
0                   97                    99  ...                73
1                   82                    79  ...                90
2                   58                    52  ...                81
3                   88                    91  ...                71
4                   70                    73  ...                84
5                   86                    90  ...                93
6                   67                    65  ...                99
7                   80                    78  ...                95
8                   48                    46  ...                94
9                   92                    90  ...                98
10                  73                    76  ...                65
11                  71                    68  ...                80
12                  84                    88  ...                94
13                  81                    79  ...                66
14                  56                    54  ...                96
15                  94                    92  ...                94
16                  66                    63  ...                92
17                  74                    77  ...                86
18                  83                    81  ...                92
19                  91                    88  ...                99

    history_score_right  physics_score_right chemistry_score_right  \
0                    81                   93                    97
1                    86                   96                   100
2                    97                   95                    96
3                    74                   88                    80
4                    77                   65                    65
5                   100                   67                    78
6                    96                   97                    73
7                    95                   82                    63
8                    68                   94                    85
9                    69                   88                    71
10                   60                   97                    94
11                   61                  100                    65
12                   59                   69                    67
13                   94                   86                   100
14                   90                   86                    92
15                   50                   78                    64
16                   64                   93                    91
17                   83                   85                    79
18                   87                   92                    99
19                   65                   98                    75

    biology_score_right  english_score_right  geography_score_right  \
0                    63                   80                     87
1                    90                   88                     90
2                    65                   77                     94
3                    89                   63                     86
4                    80                   74                     76
5                    72                   80                     84
6                    88                   76                     64
7                    84                   70                     85
8                    81                   74                     72
9                    67                   71                     73
10                   71                   81                     66
11                   87                   64                     61
12                   89                   65                     73
13                   57                   90                     63
14                   92                   95                     87
15                   79                   74                     84
16                   80                   89                     72
17                   93                   76                     77
18                   97                   87                     86
19                   66                   72                    100

    Grade_right  Gender_right          Email_right
0          Good          Male   student1@gmail.com
1     Excellent          Male   student2@gmail.com
2          Good        Female   student3@gmail.com
3          Good        Female   student4@gmail.com
4          Good        Female   student5@gmail.com
5          Good          Male   student6@gmail.com
6          Good        Female   student7@gmail.com
7          Good        Female   student8@gmail.com
8          Good        Female   student9@gmail.com
9          Good        Female  student10@gmail.com
10         Good        Female  student11@gmail.com
11         Good        Female  student12@gmail.com
12         Good        Female  student13@gmail.com
13         Good        Female  student14@gmail.com
14    Excellent          Male  student15@gmail.com
15         Good          Male  student16@gmail.com
16         Good          Male  student17@gmail.com
17         Good        Female  student18@gmail.com
18    Excellent          Male  student19@gmail.com
19         Good          Male  student20@gmail.com

[20 rows x 26 columns]

In [51]:
pd.concat([df1,df2])

,Id,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
0,1,Abi,abi1@gmail.com,Female,10,100,98,97,99,100,100,98,A+
1,2,Ram,ram2@gmail.com,Male,4,78,80,82,79,85,81,77,A
2,3,Priya,priya3@gmail.com,Female,1,50,55,58,52,60,57,54,C
3,4,Divya,divya4@gmail.com,Female,5,90,92,88,91,94,89,93,A+
4,5,Kavin,kavin5@gmail.com,Male,3,72,74,70,73,76,71,75,B+
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,NaN,student1495@gmail.com,Male,15,85,76,94,89,85,83,80,Good
1495,1496,NaN,student1496@gmail.com,Male,30,80,84,82,69,91,80,96,Good
1496,1497,NaN,student1497@gmail.com,Male,31,99,61,91,73,89,62,82,Good
1497,1498,NaN,student1498@gmail.com,Female,23,70,91,81,61,64,93,96,Good
1498,1499,NaN,student1499@gmail.com,Female,23,62,72,78,96,70,74,72,Good

In [52]:
df["Student_Name"]

0         Abi
1         Ram
2       Priya
3       Divya
4       Kavin
5       Meena
6       Arjun
7       Sneha
8       Rahul
9         Anu
10     Seeman
11    Keerthi
12      Vicky
13      Nisha
14       Hari
15    Lavanya
16       Ajay
17      Pooja
18     Sanjay
19      Rekha
Name: Student_Name, dtype: object

In [53]:
df.fillna(0)

,Id,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
0,1,Abi,abi1@gmail.com,Female,10,100,98,97,99,100,100,98,A+
1,2,Ram,ram2@gmail.com,Male,4,78,80,82,79,85,81,77,A
2,3,Priya,priya3@gmail.com,Female,1,50,55,58,52,60,57,54,C
3,4,Divya,divya4@gmail.com,Female,5,90,92,88,91,94,89,93,A+
4,5,Kavin,kavin5@gmail.com,Male,3,72,74,70,73,76,71,75,B+
5,6,Meena,meena6@gmail.com,Female,6,88,84,86,90,89,85,87,A
6,7,Arjun,arjun7@gmail.com,Male,2,61,63,67,65,68,70,66,B
7,8,Sneha,sneha8@gmail.com,Female,4,79,82,80,78,84,83,81,A
8,9,Rahul,rahul9@gmail.com,Male,1,45,50,48,46,52,49,47,C
9,10,Anu,anu10@gmail.com,Female,5,91,89,92,90,95,93,94,A+
10,11,Seeman,seeman11@gmail.com,Male,3,74,71,73,76,72,75,70,B+
11,12,Keerthi,keerthi12@gmail.com,Female,2,67,69,71,68,73,74,72,B
12,13,Vicky,vicky13@gmail.com,Male,6,85,87,84,88,90,86,89,A
13,14,Nisha,nisha14@gmail.com,Female,4,80,83,81,79,82,84,80,A
14,15,Hari,hari15@gmail.com,Male,1,55,58,56,54,60,57,59,C+
15,16,Lavanya,lavanya16@gmail.com,Female,5,93,91,94,92,96,95,97,A+
16,17,Ajay,ajay17@gmail.com,Male,2,62,64,66,63,67,68,65,B
17,18,Pooja,pooja18@gmail.com,Female,3,76,78,74,77,79,80,75,B+
18,19,Sanjay,sanjay19@gmail.com,Male,4,82,85,83,81,86,84,82,A
19,20,Rekha,rekha20@gmail.com,Female,6,89,90,91,88,92,93,90,A+

In [55]:
df.sort_values("math_score")

,Id,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
8,9,Rahul,rahul9@gmail.com,Male,1,45,50,48,46,52,49,47,C
2,3,Priya,priya3@gmail.com,Female,1,50,55,58,52,60,57,54,C
14,15,Hari,hari15@gmail.com,Male,1,55,58,56,54,60,57,59,C+
6,7,Arjun,arjun7@gmail.com,Male,2,61,63,67,65,68,70,66,B
16,17,Ajay,ajay17@gmail.com,Male,2,62,64,66,63,67,68,65,B
11,12,Keerthi,keerthi12@gmail.com,Female,2,67,69,71,68,73,74,72,B
4,5,Kavin,kavin5@gmail.com,Male,3,72,74,70,73,76,71,75,B+
10,11,Seeman,seeman11@gmail.com,Male,3,74,71,73,76,72,75,70,B+
17,18,Pooja,pooja18@gmail.com,Female,3,76,78,74,77,79,80,75,B+
1,2,Ram,ram2@gmail.com,Male,4,78,80,82,79,85,81,77,A
7,8,Sneha,sneha8@gmail.com,Female,4,79,82,80,78,84,83,81,A
13,14,Nisha,nisha14@gmail.com,Female,4,80,83,81,79,82,84,80,A
18,19,Sanjay,sanjay19@gmail.com,Male,4,82,85,83,81,86,84,82,A
12,13,Vicky,vicky13@gmail.com,Male,6,85,87,84,88,90,86,89,A
5,6,Meena,meena6@gmail.com,Female,6,88,84,86,90,89,85,87,A
19,20,Rekha,rekha20@gmail.com,Female,6,89,90,91,88,92,93,90,A+
3,4,Divya,divya4@gmail.com,Female,5,90,92,88,91,94,89,93,A+
9,10,Anu,anu10@gmail.com,Female,5,91,89,92,90,95,93,94,A+
15,16,Lavanya,lavanya16@gmail.com,Female,5,93,91,94,92,96,95,97,A+
0,1,Abi,abi1@gmail.com,Female,10,100,98,97,99,100,100,98,A+

In [56]:
df.isnull()

,Id,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False

In [57]:
df.size

260

In [59]:
df.insert(1,"Age",[20]*20)

In [60]:
df

,Id,Age,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
0,1,20,Abi,abi1@gmail.com,Female,10,100,98,97,99,100,100,98,A+
1,2,20,Ram,ram2@gmail.com,Male,4,78,80,82,79,85,81,77,A
2,3,20,Priya,priya3@gmail.com,Female,1,50,55,58,52,60,57,54,C
3,4,20,Divya,divya4@gmail.com,Female,5,90,92,88,91,94,89,93,A+
4,5,20,Kavin,kavin5@gmail.com,Male,3,72,74,70,73,76,71,75,B+
5,6,20,Meena,meena6@gmail.com,Female,6,88,84,86,90,89,85,87,A
6,7,20,Arjun,arjun7@gmail.com,Male,2,61,63,67,65,68,70,66,B
7,8,20,Sneha,sneha8@gmail.com,Female,4,79,82,80,78,84,83,81,A
8,9,20,Rahul,rahul9@gmail.com,Male,1,45,50,48,46,52,49,47,C
9,10,20,Anu,anu10@gmail.com,Female,5,91,89,92,90,95,93,94,A+
10,11,20,Seeman,seeman11@gmail.com,Male,3,74,71,73,76,72,75,70,B+
11,12,20,Keerthi,keerthi12@gmail.com,Female,2,67,69,71,68,73,74,72,B
12,13,20,Vicky,vicky13@gmail.com,Male,6,85,87,84,88,90,86,89,A
13,14,20,Nisha,nisha14@gmail.com,Female,4,80,83,81,79,82,84,80,A
14,15,20,Hari,hari15@gmail.com,Male,1,55,58,56,54,60,57,59,C+
15,16,20,Lavanya,lavanya16@gmail.com,Female,5,93,91,94,92,96,95,97,A+
16,17,20,Ajay,ajay17@gmail.com,Male,2,62,64,66,63,67,68,65,B
17,18,20,Pooja,pooja18@gmail.com,Female,3,76,78,74,77,79,80,75,B+
18,19,20,Sanjay,sanjay19@gmail.com,Male,4,82,85,83,81,86,84,82,A
19,20,20,Rekha,rekha20@gmail.com,Female,6,89,90,91,88,92,93,90,A+

In [63]:
df.replace(90,100)

,Id,Age,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
0,1,20,Abi,abi1@gmail.com,Female,10,100,98,97,99,100,100,98,A+
1,2,20,Ram,ram2@gmail.com,Male,4,78,80,82,79,85,81,77,A
2,3,20,Priya,priya3@gmail.com,Female,1,50,55,58,52,60,57,54,C
3,4,20,Divya,divya4@gmail.com,Female,5,100,92,88,91,94,89,93,A+
4,5,20,Kavin,kavin5@gmail.com,Male,3,72,74,70,73,76,71,75,B+
5,6,20,Meena,meena6@gmail.com,Female,6,88,84,86,100,89,85,87,A
6,7,20,Arjun,arjun7@gmail.com,Male,2,61,63,67,65,68,70,66,B
7,8,20,Sneha,sneha8@gmail.com,Female,4,79,82,80,78,84,83,81,A
8,9,20,Rahul,rahul9@gmail.com,Male,1,45,50,48,46,52,49,47,C
9,10,20,Anu,anu10@gmail.com,Female,5,91,89,92,100,95,93,94,A+
10,11,20,Seeman,seeman11@gmail.com,Male,3,74,71,73,76,72,75,70,B+
11,12,20,Keerthi,keerthi12@gmail.com,Female,2,67,69,71,68,73,74,72,B
12,13,20,Vicky,vicky13@gmail.com,Male,6,85,87,84,88,100,86,89,A
13,14,20,Nisha,nisha14@gmail.com,Female,4,80,83,81,79,82,84,80,A
14,15,20,Hari,hari15@gmail.com,Male,1,55,58,56,54,60,57,59,C+
15,16,20,Lavanya,lavanya16@gmail.com,Female,5,93,91,94,92,96,95,97,A+
16,17,20,Ajay,ajay17@gmail.com,Male,2,62,64,66,63,67,68,65,B
17,18,20,Pooja,pooja18@gmail.com,Female,3,76,78,74,77,79,80,75,B+
18,19,20,Sanjay,sanjay19@gmail.com,Male,4,82,85,83,81,86,84,82,A
19,20,20,Rekha,rekha20@gmail.com,Female,6,89,100,91,88,92,93,100,A+

In [69]:
df=df.assign(Age=[25]*20)

In [70]:
df

,Id,Age,Student_Name,Email,Gender,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade
0,1,25,Abi,abi1@gmail.com,Female,10,100,98,97,99,100,100,98,A+
1,2,25,Ram,ram2@gmail.com,Male,4,78,80,82,79,85,81,77,A
2,3,25,Priya,priya3@gmail.com,Female,1,50,55,58,52,60,57,54,C
3,4,25,Divya,divya4@gmail.com,Female,5,90,92,88,91,94,89,93,A+
4,5,25,Kavin,kavin5@gmail.com,Male,3,72,74,70,73,76,71,75,B+
5,6,25,Meena,meena6@gmail.com,Female,6,88,84,86,90,89,85,87,A
6,7,25,Arjun,arjun7@gmail.com,Male,2,61,63,67,65,68,70,66,B
7,8,25,Sneha,sneha8@gmail.com,Female,4,79,82,80,78,84,83,81,A
8,9,25,Rahul,rahul9@gmail.com,Male,1,45,50,48,46,52,49,47,C
9,10,25,Anu,anu10@gmail.com,Female,5,91,89,92,90,95,93,94,A+
10,11,25,Seeman,seeman11@gmail.com,Male,3,74,71,73,76,72,75,70,B+
11,12,25,Keerthi,keerthi12@gmail.com,Female,2,67,69,71,68,73,74,72,B
12,13,25,Vicky,vicky13@gmail.com,Male,6,85,87,84,88,90,86,89,A
13,14,25,Nisha,nisha14@gmail.com,Female,4,80,83,81,79,82,84,80,A
14,15,25,Hari,hari15@gmail.com,Male,1,55,58,56,54,60,57,59,C+
15,16,25,Lavanya,lavanya16@gmail.com,Female,5,93,91,94,92,96,95,97,A+
16,17,25,Ajay,ajay17@gmail.com,Male,2,62,64,66,63,67,68,65,B
17,18,25,Pooja,pooja18@gmail.com,Female,3,76,78,74,77,79,80,75,B+
18,19,25,Sanjay,sanjay19@gmail.com,Male,4,82,85,83,81,86,84,82,A
19,20,25,Rekha,rekha20@gmail.com,Female,6,89,90,91,88,92,93,90,A+