In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("/content/student-scores_DATASET(cleaned).csv")

In [3]:
df

,Id,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [5]:
df.head()

,Id,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,84,77,65,65,80,74,76,Good,Female,student5@gmail.com

In [6]:
df.tail()

,Id,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
1494,1495,15,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [7]:
df.shape

(1499, 12)

In [8]:
df.columns

Index(['Id', 'weekly_self_study_hours', 'math_score', 'history_score',
       'physics_score', 'chemistry_score', 'biology_score', 'english_score',
       'geography_score', 'Grade', 'Gender', 'Email'],
      dtype='object')

In [9]:
df.dtypes

Id                          int64
weekly_self_study_hours     int64
math_score                  int64
history_score               int64
physics_score               int64
chemistry_score             int64
biology_score               int64
english_score               int64
geography_score             int64
Grade                      object
Gender                     object
Email                      object
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1499 entries, 0 to 1498
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Id                       1499 non-null   int64
 1   weekly_self_study_hours  1499 non-null   int64
 2   math_score               1499 non-null   int64
 3   history_score            1499 non-null   int64
 4   physics_score            1499 non-null   int64
 5   chemistry_score          1499 non-null   int64
 6   biology_score            1499 non-null   int64
 7   english_score            1499 non-null   int64
 8   geography_score          1499 non-null   int64
 9   Grade                    1499 non-null   object
 10  Gender                   1499 non-null   object
 11  Email                    1499 non-null   object
dtypes: int64(9), object(3)
memory usage: 140.7+ KB

In [11]:
df.describe()

,Id,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
count,1499.00000,1499.000000,1499.000000,1499.000000,1499.000000,1499.000000,1499.000000,1499.000000,1499.000000
mean,750.00000,17.779186,83.497665,80.075384,81.386925,79.939293,79.176117,81.354903,81.026017
std,432.86834,12.044253,13.278338,12.648754,12.541562,12.771105,13.816978,11.952878,11.728970
min,1.00000,0.000000,40.000000,50.000000,50.000000,50.000000,30.000000,50.000000,60.000000
25%,375.50000,5.000000,76.500000,69.000000,71.000000,69.000000,69.000000,72.000000,71.000000
50%,750.00000,18.000000,87.000000,81.000000,83.000000,81.000000,80.000000,83.000000,81.000000
75%,1124.50000,28.000000,94.000000,91.000000,92.000000,91.000000,91.000000,91.000000,91.000000
max,1499.00000,50.000000,100.000000,100.000000,100.000000,100.000000,100.000000,99.000000,100.000000

In [12]:
df.isnull()

,Id,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1494,False,False,False,False,False,False,False,False,False,False,False,False
1495,False,False,False,False,False,False,False,False,False,False,False,False
1496,False,False,False,False,False,False,False,False,False,False,False,False
1497,False,False,False,False,False,False,False,False,False,False,False,False
1498,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
df["math_score"].sum()

np.int64(125163)

In [15]:
df["weekly_self_study_hours"].mean()

np.float64(17.77918612408272)

In [17]:
df["Gender"].mode()

0    Female
Name: Gender, dtype: object

In [18]:
df["history_score"].max()

100

In [19]:
df["physics_score"].min()

50

In [20]:
df["Id"].count()

np.int64(1499)

In [21]:
df["geography_score"].std()

11.728970481124724

In [22]:
df["english_score"].var()

142.87128935979777

In [23]:
df["Grade"].unique()

array(['Good', 'Excellent', 'Average'], dtype=object)

In [24]:
df.sort_values("chemistry_score")

,Id,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
41,42,4,65,55,66,50,88,56,86,Average,Male,student42@gmail.com
1163,1164,4,71,89,63,50,63,64,69,Average,Female,student1164@gmail.com
819,820,2,46,71,60,50,85,69,62,Average,Male,student820@gmail.com
644,645,0,82,74,92,50,77,98,100,Good,Male,student645@gmail.com
1340,1341,0,79,67,72,50,75,95,62,Good,Male,student1341@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
361,362,30,100,86,81,100,66,98,97,Excellent,Female,student362@gmail.com
355,356,5,100,58,58,100,60,52,82,Good,Female,student356@gmail.com
1102,1103,32,78,92,77,100,61,82,61,Good,Female,student1103@gmail.com
1,2,47,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
1492,1493,21,100,82,84,100,90,62,87,Good,Female,student1493@gmail.com

In [25]:
df.sort_index()

,Id,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [26]:
df.drop("Email",axis=1)

,Id,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender
0,1,27,73,81,93,97,63,80,87,Good,Male
1,2,47,90,86,96,100,90,88,90,Excellent,Male
2,3,13,81,97,95,96,65,77,94,Good,Female
3,4,3,71,74,88,80,89,63,86,Good,Female
4,5,10,84,77,65,65,80,74,76,Good,Female
...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,85,76,94,89,85,83,80,Good,Male
1495,1496,30,80,84,82,69,91,80,96,Good,Male
1496,1497,31,99,61,91,73,89,62,82,Good,Male
1497,1498,23,70,91,81,61,64,93,96,Good,Female
1498,1499,23,62,72,78,96,70,74,72,Good,Female

In [27]:
df.drop_duplicates()

,Id,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [28]:
df.rename(columns={"weekly_self_study_hours":"Study_Hours"})

,Id,Study_Hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [37]:
df.insert(2,"Age",[20]*1499)

ValueError: cannot insert Age, already exists

In [38]:
df

,Id,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,20,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,20,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,20,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,20,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,20,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,20,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,20,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,20,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,20,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,20,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [39]:
df.replace(90,100)

,Id,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,20,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,20,100,86,96,100,100,88,100,Excellent,Male,student2@gmail.com
2,3,13,20,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,20,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,20,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,20,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,20,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,20,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,20,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,20,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [40]:
df.query("math_score>90")

,Id,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
5,6,26,20,93,100,67,78,72,80,84,Good,Male,student6@gmail.com
6,7,23,20,99,96,97,73,88,76,64,Good,Female,student7@gmail.com
7,8,34,20,95,95,82,63,84,70,85,Good,Female,student8@gmail.com
8,9,25,20,94,68,94,85,81,74,72,Good,Female,student9@gmail.com
9,10,18,20,98,69,88,71,67,71,73,Good,Female,student10@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1488,1489,27,20,96,92,80,61,66,98,70,Good,Female,student1489@gmail.com
1491,1492,4,20,92,96,80,98,61,84,74,Good,Male,student1492@gmail.com
1492,1493,21,20,100,82,84,100,90,62,87,Good,Female,student1493@gmail.com
1493,1494,31,20,94,63,98,73,63,98,100,Good,Male,student1494@gmail.com
1496,1497,31,20,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com

In [41]:
df.sample(1)

,Id,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
1355,1356,11,20,76,82,74,79,81,93,72,Good,Female,student1356@gmail.com

In [42]:
df.loc[0]

Id                                          1
weekly_self_study_hours                    27
Age                                        20
math_score                                 73
history_score                              81
physics_score                              93
chemistry_score                            97
biology_score                              63
english_score                              80
geography_score                            87
Grade                                    Good
Gender                                   Male
Email                      student1@gmail.com
Name: 0, dtype: object

In [45]:
df.groupby("Id").sum()

,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
Id,,,,,,,,,,,,
1,27,20,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
2,47,20,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
3,13,20,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
4,3,20,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
5,10,20,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,15,20,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1496,30,20,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1497,31,20,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1498,23,20,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1499,23,20,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [46]:
pd.concat([df,df])

,Id,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,20,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,20,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,20,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,20,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,20,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,20,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,20,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,20,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,20,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,20,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [47]:
df2=pd.read_csv("/content/student-scores_DATASET(cleaned).csv")

In [48]:
df2

,Id,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [49]:
pd.merge(df,df2,on="Id")

,Id,weekly_self_study_hours_x,Age,math_score_x,history_score_x,physics_score_x,chemistry_score_x,biology_score_x,english_score_x,geography_score_x,...,math_score_y,history_score_y,physics_score_y,chemistry_score_y,biology_score_y,english_score_y,geography_score_y,Grade_y,Gender_y,Email_y
0,1,27,20,73,81,93,97,63,80,87,...,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,20,90,86,96,100,90,88,90,...,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,20,81,97,95,96,65,77,94,...,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,20,71,74,88,80,89,63,86,...,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,20,84,77,65,65,80,74,76,...,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,20,85,76,94,89,85,83,80,...,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,20,80,84,82,69,91,80,96,...,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,20,99,61,91,73,89,62,82,...,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,20,70,91,81,61,64,93,96,...,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,20,62,72,78,96,70,74,72,...,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [51]:
df["Age"].astype(float)

0       20.0
1       20.0
2       20.0
3       20.0
4       20.0
        ...
1494    20.0
1495    20.0
1496    20.0
1497    20.0
1498    20.0
Name: Age, Length: 1499, dtype: float64

In [52]:
df.to_numpy()

array([[1, 27, 20, ..., 'Good', 'Male', 'student1@gmail.com'],
       [2, 47, 20, ..., 'Excellent', 'Male', 'student2@gmail.com'],
       [3, 13, 20, ..., 'Good', 'Female', 'student3@gmail.com'],
       ...,
       [1497, 31, 20, ..., 'Good', 'Male', 'student1497@gmail.com'],
       [1498, 23, 20, ..., 'Good', 'Female', 'student1498@gmail.com'],
       [1499, 23, 20, ..., 'Good', 'Female', 'student1499@gmail.com']],
      dtype=object)

In [56]:
df[df["history_score"]>80]

,Id,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,20,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,20,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,20,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
5,6,26,20,93,100,67,78,72,80,84,Good,Male,student6@gmail.com
6,7,23,20,99,96,97,73,88,76,64,Good,Female,student7@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1489,1490,29,20,90,84,90,81,92,83,69,Good,Female,student1490@gmail.com
1491,1492,4,20,92,96,80,98,61,84,74,Good,Male,student1492@gmail.com
1492,1493,21,20,100,82,84,100,90,62,87,Good,Female,student1493@gmail.com
1495,1496,30,20,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1497,1498,23,20,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com

In [57]:

df[df["english_score"]==90]

,Id,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
13,14,2,20,66,94,86,100,57,90,63,Good,Female,student14@gmail.com
25,26,22,20,92,86,87,81,93,90,99,Good,Male,student26@gmail.com
26,27,34,20,100,77,80,94,63,90,90,Good,Female,student27@gmail.com
102,103,29,20,76,87,64,74,73,90,99,Good,Female,student103@gmail.com
110,111,24,20,76,89,89,83,89,90,64,Good,Male,student111@gmail.com
120,121,13,20,66,90,83,80,76,90,91,Good,Female,student121@gmail.com
134,135,3,20,87,62,87,96,85,90,74,Good,Male,student135@gmail.com
137,138,11,20,79,97,76,67,61,90,95,Good,Male,student138@gmail.com
152,153,18,20,91,100,84,72,84,90,82,Good,Male,student153@gmail.com
176,177,15,20,97,92,95,75,95,90,83,Good,Female,student177@gmail.com
190,191,1,20,99,82,93,83,92,90,60,Good,Male,student191@gmail.com
221,222,22,20,95,87,79,95,84,90,74,Good,Male,student222@gmail.com
222,223,33,20,99,61,75,68,66,90,99,Good,Male,student223@gmail.com
233,234,16,20,98,88,92,84,90,90,71,Good,Female,student234@gmail.com
253,254,21,20,76,72,80,92,41,90,78,Good,Female,student254@gmail.com
289,290,16,20,92,70,60,94,87,90,86,Good,Female,student290@gmail.com
297,298,2,20,97,74,97,60,65,90,97,Good,Female,student298@gmail.com
299,300,20,20,88,60,81,85,87,90,76,Good,Female,student300@gmail.com
307,308,43,20,90,96,100,87,100,90,89,Excellent,Female,student308@gmail.com
340,341,15,20,73,75,94,82,71,90,75,Good,Male,student341@gmail.com
375,376,29,20,77,87,65,91,71,90,90,Good,Female,student376@gmail.com
418,419,24,20,86,99,95,94,92,90,77,Excellent,Female,student419@gmail.com
419,420,35,20,92,97,100,91,95,90,95,Excellent,Male,student420@gmail.com
435,436,28,20,88,90,93,81,88,90,74,Good,Male,student436@gmail.com
459,460,32,20,72,72,68,81,95,90,99,Good,Female,student460@gmail.com
468,469,29,20,85,82,81,85,72,90,71,Good,Female,student469@gmail.com
489,490,0,20,100,67,50,78,73,90,91,Good,Male,student490@gmail.com
553,554,15,20,94,71,63,73,66,90,91,Good,Female,student554@gmail.com
577,578,47,20,85,87,92,96,92,90,88,Excellent,Male,student578@gmail.com
616,617,2,20,72,51,52,98,50,90,63,Average,Female,student617@gmail.com
647,648,23,20,86,89,94,95,60,90,90,Good,Female,student648@gmail.com
649,650,30,20,77,95,77,84,60,90,89,Good,Female,student650@gmail.com
673,674,24,20,100,89,90,96,72,90,86,Excellent,Female,student674@gmail.com
693,694,14,20,93,79,82,67,64,90,65,Good,Male,student694@gmail.com
804,805,27,20,94,94,86,62,73,90,75,Good,Female,student805@gmail.com
880,881,0,20,93,96,70,92,65,90,84,Good,Female,student881@gmail.com
885,886,20,20,93,61,65,77,97,90,90,Good,Female,student886@gmail.com
969,970,35,20,91,97,87,93,94,90,88,Excellent,Female,student970@gmail.com
972,973,29,20,87,89,61,66,72,90,61,Good,Female,student973@gmail.com
1105,1106,32,20,83,63,93,94,93,90,78,Good,Female,student1106@gmail.com
1134,1135,28,20,87,99,70,81,62,90,91,Good,Female,student1135@gmail.com
1136,1137,31,20,77,98,67,67,80,90,66,Good,Female,student1137@gmail.com
1179,1180,38,20,96,92,93,91,88,90,88,Excellent,Female,student1180@gmail.com
1199,1200,35,20,99,89,93,87,86,90,96,Excellent,Female,student1200@gmail.com
1204,1205,27,20,96,70,82,71,99,90,65,Good,Female,student1205@gmail.com
1223,1224,28,20,100,94,76,60,95,90,66,Good,Female,student1224@gmail.com
1251,1252,21,20,69,77,82,93,92,90,71,Good,Male,student1252@gmail.com
1282,1283,3,20,80,85,85,60,77,90,81,Good,Male,student1283@gmail.com
1296,1297,21,20,83,81,96,62,66,90,91,Good,Male,student1297@gmail.com
1299,1300,31,20,81,92,97,73,90,90,60,Good,Male,student1300@gmail.com
1327,1328,15,20,69,81,83,68,76,90,95,Good,Male,student1328@gmail.com
1331,1332,29,20,82,93,67,79,84,90,64,Good,Female,student1332@gmail.com
1352,1353,9,20,58,81,100,97,74,90,87,Good,Male,student1353@gmail.com
1380,1381,23,20,99,75,79,87,63,90,90,Good,Male,student1381@gmail.com
1389,1390,13,20,78,89,83,80,67,90,93,Good,Female,student1390@gmail.com
1420,1421,3,20,73,70,80,74,71,90,80,Good,Female,student1421@gmail.com

In [62]:
df["Email"]

0          student1@gmail.com
1          student2@gmail.com
2          student3@gmail.com
3          student4@gmail.com
4          student5@gmail.com
                ...
1494    student1495@gmail.com
1495    student1496@gmail.com
1496    student1497@gmail.com
1497    student1498@gmail.com
1498    student1499@gmail.com
Name: Email, Length: 1499, dtype: object

In [63]:
df[["Id","Gender"]]

        Id  Gender
0        1    Male
1        2    Male
2        3  Female
3        4  Female
4        5  Female
...    ...     ...
1494  1495    Male
1495  1496    Male
1496  1497    Male
1497  1498  Female
1498  1499  Female

[1499 rows x 2 columns]

In [64]:
df[df["geography_score"].between(80,90)]

,Id,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,20,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,20,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
3,4,3,20,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
5,6,26,20,93,100,67,78,72,80,84,Good,Male,student6@gmail.com
7,8,34,20,95,95,82,63,84,70,85,Good,Female,student8@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1487,1488,1,20,96,92,64,54,87,60,88,Good,Male,student1488@gmail.com
1490,1491,4,20,85,57,77,81,65,75,85,Good,Female,student1491@gmail.com
1492,1493,21,20,100,82,84,100,90,62,87,Good,Female,student1493@gmail.com
1494,1495,15,20,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1496,1497,31,20,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com

In [68]:
df["Email"].str.upper()

0          STUDENT1@GMAIL.COM
1          STUDENT2@GMAIL.COM
2          STUDENT3@GMAIL.COM
3          STUDENT4@GMAIL.COM
4          STUDENT5@GMAIL.COM
                ...
1494    STUDENT1495@GMAIL.COM
1495    STUDENT1496@GMAIL.COM
1496    STUDENT1497@GMAIL.COM
1497    STUDENT1498@GMAIL.COM
1498    STUDENT1499@GMAIL.COM
Name: Email, Length: 1499, dtype: object

In [70]:
df["Gender"].str.title()

0         Male
1         Male
2       Female
3       Female
4       Female
         ...
1494      Male
1495      Male
1496      Male
1497    Female
1498    Female
Name: Gender, Length: 1499, dtype: object

In [71]:
df["Email"].str.capitalize()

0          Student1@gmail.com
1          Student2@gmail.com
2          Student3@gmail.com
3          Student4@gmail.com
4          Student5@gmail.com
                ...
1494    Student1495@gmail.com
1495    Student1496@gmail.com
1496    Student1497@gmail.com
1497    Student1498@gmail.com
1498    Student1499@gmail.com
Name: Email, Length: 1499, dtype: object

In [72]:
df["Grade"].str.len()

0       4
1       9
2       4
3       4
4       4
       ..
1494    4
1495    4
1496    4
1497    4
1498    4
Name: Grade, Length: 1499, dtype: int64

In [73]:
df["Grade"].str.contains("A")

0       False
1       False
2       False
3       False
4       False
        ...
1494    False
1495    False
1496    False
1497    False
1498    False
Name: Grade, Length: 1499, dtype: bool

In [76]:
df["Grade"].str.startswith("G")

0        True
1       False
2        True
3        True
4        True
        ...
1494     True
1495     True
1496     True
1497     True
1498     True
Name: Grade, Length: 1499, dtype: bool

In [77]:
df.drop_duplicates()

,Id,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,20,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,20,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,20,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,20,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,20,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,20,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,20,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,20,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,20,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,20,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [78]:
df.copy()

,Id,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,20,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,20,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,20,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,20,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,20,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,20,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,20,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,20,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,20,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,20,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [79]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1494    False
1495    False
1496    False
1497    False
1498    False
Length: 1499, dtype: bool

In [80]:
df.fillna(0)

,Id,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
0,1,27,20,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
1,2,47,20,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
2,3,13,20,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
3,4,3,20,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
4,5,10,20,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1495,15,20,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1495,1496,30,20,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1496,1497,31,20,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1497,1498,23,20,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1498,1499,23,20,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [81]:
df.set_index("Id")

,weekly_self_study_hours,Age,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,Grade,Gender,Email
Id,,,,,,,,,,,,
1,27,20,73,81,93,97,63,80,87,Good,Male,student1@gmail.com
2,47,20,90,86,96,100,90,88,90,Excellent,Male,student2@gmail.com
3,13,20,81,97,95,96,65,77,94,Good,Female,student3@gmail.com
4,3,20,71,74,88,80,89,63,86,Good,Female,student4@gmail.com
5,10,20,84,77,65,65,80,74,76,Good,Female,student5@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,15,20,85,76,94,89,85,83,80,Good,Male,student1495@gmail.com
1496,30,20,80,84,82,69,91,80,96,Good,Male,student1496@gmail.com
1497,31,20,99,61,91,73,89,62,82,Good,Male,student1497@gmail.com
1498,23,20,70,91,81,61,64,93,96,Good,Female,student1498@gmail.com
1499,23,20,62,72,78,96,70,74,72,Good,Female,student1499@gmail.com

In [86]:
pd.Series([df])

0            Id  weekly_self_study_hours  Age  math...
dtype: object

In [89]:
df.nunique()

Id                         1499
weekly_self_study_hours      49
Age                           1
math_score                   61
history_score                51
physics_score                49
chemistry_score              51
biology_score                68
english_score                50
geography_score              41
Grade                         3
Gender                        2
Email                      1499
dtype: int64